name       : efivar
version    : 30
release    : 1
source     :
    - https://github.com/rhinstaller/efivar/archive/30.tar.gz : 20709c76311f8eb8be92977b7ac008ce62501fa9f7fe885a784321540fc352f9
license    : LGPL-2.1
component  : programming
summary    : Tools and libraries to manipulate EFI variables
description: |
    Tools and libraries to manipulate EFI variables
builddeps  :
    - pkgconfig(popt)
setup      : |
    %patch -p1 < $pkgfiles/muldeps.patch
build      : |
    %make efivar
install    : |
    %make_install
