name       : efivar
version    : '31'
release    : 2
source     :
    - https://github.com/rhboot/efivar/releases/download/31/efivar-31.tar.bz2 : d891958a5a762a43371987c46ca112ba506a26312d4969e6871d77acb5ea787e
license    : LGPL-2.1
component  : programming
summary    : Tools and libraries to manipulate EFI variables
description: |
    Tools and libraries to manipulate EFI variables
builddeps  :
    - pkgconfig(popt)
build      : |
    %make efivar efivar-static static -j1
install    : |
    %make_install efivar-static static -j1
    install -m 00644 src/libefi{boot,var}.a $installdir/%libdir%/.
