name       : efivar
version    : '38'
release    : 4
source     :
    - git|https://github.com/rhboot/efivar.git : 90e88b221e8bc60dc50f3246051369b8f580c0d0
license    : LGPL-2.1-or-later
component  : system.base
summary    : Tools and libraries to manipulate EFI variables
description: |
    Tools and libraries to manipulate EFI variables
setup      : |
    %patch -p1 < $pkgfiles/allow-disabling-mandoc.patch
build      : |
    %make ENABLE_DOCS=0 efivar efivar-static static -j1
install    : |
    %make_install ENABLE_DOCS=0 efivar-static static -j1
    install -m 00644 src/libefi{boot,var}.a $installdir/%libdir%/.
